export const SELECT_CATEGORY = 'SELECT_CATEGORY'
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'

export const POST_SORT_LIST = 'POST_SORT_LIST'
export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POST_DETAIL = 'FETCH_POST_DETAIL'
export const SUBMIT_POST = 'SUBMIT_POST'
export const VOTE_POST = 'VOTE_POST'

export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS'

export const SUBMIT_COMMENT = 'SUBMIT_COMMENT'
export const VOTE_COMMENT = 'VOTE_COMMENT'
export const SORT_COMMENTS = 'SORT_COMMENTS'
